#lang scheme

(define (average a b)
	(/ (+ a b) 2))
(define tolerance 0.00001)
(define (fixed-point f first-guess)
	(define (close-enough? v1 v2)
		(< (abs (- v1 v2)) tolerance))
	(define (try guess)
		(newline)
		(display guess)
		(newline)
		(let ((next (f guess)))
			(if (close-enough? guess next)
				next
				(try next))))
	(try first-guess))
(define (golden x)
	(fixed-point (lambda (x) (+ 1 (/ 1 x)))
							 1.0))
(golden 1)
